/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNotificationCenter: typeof import('./src/components/admin/AdminNotificationCenter.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    ApplicationModal: typeof import('./src/components/support/ApplicationModal.vue')['default']
    CHEAlert: typeof import('./src/components/alerts/CHEAlert.vue')['default']
    ClaimModal: typeof import('./src/components/support/ClaimModal.vue')['default']
    ConditionModal: typeof import('./src/components/support/ConditionModal.vue')['default']
    ExpenseFilter: typeof import('./src/components/expense/ExpenseFilter.vue')['default']
    ExpenseForm: typeof import('./src/components/expense/ExpenseForm.vue')['default']
    FileUpload: typeof import('./src/components/common/FileUpload.vue')['default']
    IncomeFilter: typeof import('./src/components/income/IncomeFilter.vue')['default']
    IncomeForm: typeof import('./src/components/income/IncomeForm.vue')['default']
    MedicalCategorization: typeof import('./src/components/expense/MedicalCategorization.vue')['default']
    NotificationCenter: typeof import('./src/components/common/NotificationCenter.vue')['default']
    PathwayDetailsModal: typeof import('./src/components/support/PathwayDetailsModal.vue')['default']
    QuickActionButton: typeof import('./src/components/QuickActionButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemeDetailsModal: typeof import('./src/components/support/SchemeDetailsModal.vue')['default']
    SearchBox: typeof import('./src/components/common/SearchBox.vue')['default']
    SupportFilter: typeof import('./src/components/support/SupportFilter.vue')['default']
    ThemeSelector: typeof import('./src/components/common/ThemeSelector.vue')['default']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
  }
}
